name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-tests-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install API deps and pytest
        working-directory: services/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run API unit tests (mocked DB)
        working-directory: services/api
        run: pytest -q

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Build Docker images
        run: |
          docker build -t aoi-api -f services/api/Dockerfile services/api
          docker build -t aoi-ingest -f ingest/Dockerfile ingest
          docker build -t aoi-web -f frontend/Dockerfile frontend

